### ISSUE TITLE
插件使用报错

### ISSUE THREAD

**Issue by wxq851685279** [fangzhengjin/umi-plugin-panel-tabs#1]
![image](https://user-images.githubusercontent.com/29041799/136721737-460001ef-6774-4157-a26d-a019bdabfea0.png)

**Comment by wxq851685279** [comment]
![image](https://user-images.githubusercontent.com/29041799/136721940-798144f2-e1f9-497b-afaa-efcfebeb389d.png)

**Comment by fangzhengjin** [comment]
按文档把useAuth打开试试

**Comment by fangzhengjin** [comment]
如果还不行 可以提供个在线的仓库demo
