### ISSUE TITLE
把菜单改成服务器获取,顶部多页tabs菜单文案不能正常显示，显示成了路由名字[Bug]

### ISSUE THREAD

**Issue by ajunc** [fangzhengjin/umi-plugin-panel-tabs#11]
```
// 路由配置
{
          name: 'SerialNumberQuery',
          icon: 'smile',
          path: '/StockControl/SerialNumberQuery',
          component: './StockControl/SerialNumberQuery',
}
```
接口返回如下：
```
{
          "id":1100,
          "gmtCreate":"2022-02-15 11:26:19",
          "gmtModified":"2022-02-15 11:26:19",
          "isDeleted":0,
          "menuName":"库存管理",
          "name":"StockControl",
          "path":"StockControl",
          "icon":"dashboard",
          "parentId":0,
          "type":0,
          "check":0,
          "status":1,
          "priority":0,
          "redirect":null,
          "remark":"",
          "en":"",
          "routes":[
              {
                  "id":1105,
                  "gmtCreate":"2022-02-22 14:29:34",
                  "gmtModified":"2022-02-22 14:29:34",
                  "isDeleted":0,
                  "menuName":"SerialNumberQuery",
                  "name":"SerialNumberQuery",
                  "path":"/StockControl/SerialNumberQuery",
                  "icon":"smile",
                  "parentId":1100,
                  "type":0,
                  "check":0,
                  "status":1,
                  "priority":0,
                  "redirect":null,
                  "remark":null,
                  "en":null,
                  "routes":null
              }
      ]
}

```

在app.jsx中使用menu：
```
import { PageLoading } from '@ant-design/pro-layout';
import { history, Link } from 'umi';
import RightContent from '@/components/RightContent';
import Footer from '@/components/Footer';
import { currentUser as queryCurrentUser } from './services/ant-design-pro/api';
import { BookOutlined, LinkOutlined } from '@ant-design/icons';
import fixMenuItemIcon from './utils/fixMenuItemIcon';
const isDev = process.env.NODE_ENV === 'development';
const loginPath = '/user/login';
/** 获取用户信息比较慢的时候会展示一个 loading */
let menuData = [];

export const initialStateConfig = {
  loading: <PageLoading />,
};
/**
 * @see  https://umijs.org/zh-CN/plugins/plugin-initial-state
 * */

export async function getInitialState() {
  const fetchUserInfo = async () => {
    try {
      const msg = await queryCurrentUser();
      msg.data.data.menuData = [...msg.data.data.menuData];
      menuData = msg && msg.data && msg.data.data && msg.data.data.menuData;
      return msg.data;
    } catch (error) {
      history.push(loginPath);
    }

    return undefined;
  }; // 如果是登录页面，不执行

  if (history.location.pathname !== loginPath) {
    const currentUser = await fetchUserInfo();
    return {
      fetchUserInfo,
      currentUser,
      settings: {},
    };
  }

  return {
    fetchUserInfo,
    settings: {},
  };
} // ProLayout 支持的api https://procomponents.ant.design/components/layout

export const layout = ({ initialState }) => {
  return {
    rightContentRender: () => <RightContent />,
    disableContentMargin: false,
    waterMarkProps: {
      content: initialState?.currentUser?.user?.userName,
    },
    menu: {
      // 每当 initialState?.currentUser?.userid 发生修改时重新执行 request
      params: {
        userId: initialState?.currentUser?.user?.id,
      },
      request: async (params, defaultMenuData) => {
        // initialState.currentUser 中包含了所有用户信息

        return menuData;
      },
    },
    footerRender: () => <Footer />,
    onPageChange: () => {
      const { location } = history; // 如果没有登录，重定向到 login

      if (!initialState?.currentUser && location.pathname !== loginPath) {
        history.push(loginPath);
      }
    },
    links: isDev
      ? [
          // <Link to="/umi/plugin/openapi" target="_blank">
          //   <LinkOutlined />
          //   <span>OpenAPI 文档</span>
          // </Link>,
          // <Link to="/~docs">
          //   <BookOutlined />
          //   <span>业务组件文档</span>
          // </Link>,
        ]
      : [],
    menuHeaderRender: undefined,
    menuDataRender: () => fixMenuItemIcon(menuData),
    disableContentMargin: true,
    // 自定义 403 页面
    // unAccessible: <div>unAccessible</div>,
    ...initialState?.settings,
  };
};

```

然后在顶部多页tab中不能正常显示菜单的中英文，只能显示菜单的 name属性里面的文案

**Comment by fangzhengjin** [comment]
本来就是展示name呀，你们的menuName是自己定义的，除了你们自己谁也不知道有这个属性，你们这种如果左侧能正常显示菜单中文名肯定是重写了menu的渲染吧，同理这个插件也不知道你们有这个属性，建议按ant.design规范来，如果需要国际化就去配置国际化文件



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月7日(周一) 下午2:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [fangzhengjin/umi-plugin-panel-tabs] 把菜单改成服务器获取,顶部多页tabs菜单文案不能正常显示，显示成了路由名字[Bug] (Issue #11)




 // 路由配置 {           name: 'SerialNumberQuery',           icon: 'smile',           path: '/StockControl/SerialNumberQuery',           component: './StockControl/SerialNumberQuery', }  
接口返回如下：
 {           "id":1100,           "gmtCreate":"2022-02-15 11:26:19",           "gmtModified":"2022-02-15 11:26:19",           "isDeleted":0,           "menuName":"库存管理",           "name":"StockControl",           "path":"StockControl",           "icon":"dashboard",           "parentId":0,           "type":0,           "check":0,           "status":1,           "priority":0,           "redirect":null,           "remark":"",           "en":"",           "routes":[               {                   "id":1105,                   "gmtCreate":"2022-02-22 14:29:34",                   "gmtModified":"2022-02-22 14:29:34",                   "isDeleted":0,                   "menuName":"SerialNumberQuery",                   "name":"SerialNumberQuery",                   "path":"/StockControl/SerialNumberQuery",                   "icon":"smile",                   "parentId":1100,                   "type":0,                   "check":0,                   "status":1,                   "priority":0,                   "redirect":null,                   "remark":null,                   "en":null,                   "routes":null               }       ] }  
在app.jsx中使用menu：
 import { PageLoading } from ***@***.***/pro-layout'; import { history, Link } from 'umi'; import RightContent from '@/components/RightContent'; import Footer from '@/components/Footer'; import { currentUser as queryCurrentUser } from './services/ant-design-pro/api'; import { BookOutlined, LinkOutlined } from ***@***.***/icons'; import fixMenuItemIcon from './utils/fixMenuItemIcon'; const isDev = process.env.NODE_ENV === 'development'; const loginPath = '/user/login'; /** 获取用户信息比较慢的时候会展示一个 loading */ let menuData = []; export const initialStateConfig = {   loading: <PageLoading /&gt;, }; /**  * @see  https://umijs.org/zh-CN/plugins/plugin-initial-state  * */ export async function getInitialState() {   const fetchUserInfo = async () =&gt; {     try {       const msg = await queryCurrentUser();       msg.data.data.menuData = [...msg.data.data.menuData];       menuData = msg &amp;&amp; msg.data &amp;&amp; msg.data.data &amp;&amp; msg.data.data.menuData;       return msg.data;     } catch (error) {       history.push(loginPath);     }     return undefined;   }; // 如果是登录页面，不执行   if (history.location.pathname !== loginPath) {     const currentUser = await fetchUserInfo();     return {       fetchUserInfo,       currentUser,       settings: {},     };   }   return {     fetchUserInfo,     settings: {},   }; } // ProLayout 支持的api https://procomponents.ant.design/components/layout export const layout = ({ initialState }) =&gt; {   return {     rightContentRender: () =&gt; <RightContent /&gt;,     disableContentMargin: false,     waterMarkProps: {       content: initialState?.currentUser?.user?.userName,     },     menu: {       // 每当 initialState?.currentUser?.userid 发生修改时重新执行 request       params: {         userId: initialState?.currentUser?.user?.id,       },       request: async (params, defaultMenuData) =&gt; {         // initialState.currentUser 中包含了所有用户信息         return menuData;       },     },     footerRender: () =&gt; <Footer /&gt;,     onPageChange: () =&gt; {       const { location } = history; // 如果没有登录，重定向到 login       if (!initialState?.currentUser &amp;&amp; location.pathname !== loginPath) {         history.push(loginPath);       }     },     links: isDev       ? [           // <Link to="/umi/plugin/openapi" target="_blank"&gt;           //   <LinkOutlined /&gt;           //   <span&gt;OpenAPI 文档</span&gt;           // </Link&gt;,           // <Link to="/~docs"&gt;           //   <BookOutlined /&gt;           //   <span&gt;业务组件文档</span&gt;           // </Link&gt;,         ]       : [],     menuHeaderRender: undefined,     menuDataRender: () =&gt; fixMenuItemIcon(menuData),     disableContentMargin: true,     // 自定义 403 页面     // unAccessible: <div&gt;unAccessible</div&gt;,     ...initialState?.settings,   }; };  
然后在顶部多页tab中不能正常显示菜单的中英文，只能显示菜单的 name属性里面的文案
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ajunc** [comment]
> 本来就是展示name呀，你们的menuName是自己定义的，除了你们自己谁也不知道有这个属性，你们这种如果左侧能正常显示菜单中文名肯定是重写了menu的渲染吧，同理这个插件也不知道你们有这个属性，建议按ant.design规范来，如果需要国际化就去配置国际化文件
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年3月7日(周一) 下午2:07 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [fangzhengjin/umi-plugin-panel-tabs] 把菜单改成服务器获取,顶部多页tabs菜单文案不能正常显示，显示成了路由名字[Bug] (Issue #11) // 路由配置 { name: 'SerialNumberQuery', icon: 'smile', path: '/StockControl/SerialNumberQuery', component: './StockControl/SerialNumberQuery', } 接口返回如下： { "id":1100, "gmtCreate":"2022-02-15 11:26:19", "gmtModified":"2022-02-15 11:26:19", "isDeleted":0, "menuName":"库存管理", "name":"StockControl", "path":"StockControl", "icon":"dashboard", "parentId":0, "type":0, "check":0, "status":1, "priority":0, "redirect":null, "remark":"", "en":"", "routes":[ { "id":1105, "gmtCreate":"2022-02-22 14:29:34", "gmtModified":"2022-02-22 14:29:34", "isDeleted":0, "menuName":"SerialNumberQuery", "name":"SerialNumberQuery", "path":"/StockControl/SerialNumberQuery", "icon":"smile", "parentId":1100, "type":0, "check":0, "status":1, "priority":0, "redirect":null, "remark":null, "en":null, "routes":null } ] } 在app.jsx中使用menu： import { PageLoading } from ***@***.***/pro-layout'; import { history, Link } from 'umi'; import RightContent from '@/components/RightContent'; import Footer from '@/components/Footer'; import { currentUser as queryCurrentUser } from './services/ant-design-pro/api'; import { BookOutlined, LinkOutlined } from ***@***.***/icons'; import fixMenuItemIcon from './utils/fixMenuItemIcon'; const isDev = process.env.NODE_ENV === 'development'; const loginPath = '/user/login'; /** 获取用户信息比较慢的时候会展示一个 loading */ let menuData = []; export const initialStateConfig = { loading: <PageLoading /&gt;, }; /** * @see https://umijs.org/zh-CN/plugins/plugin-initial-state * */ export async function getInitialState() { const fetchUserInfo = async () =&gt; { try { const msg = await queryCurrentUser(); msg.data.data.menuData = [...msg.data.data.menuData]; menuData = msg &amp;&amp; msg.data &amp;&amp; msg.data.data &amp;&amp; msg.data.data.menuData; return msg.data; } catch (error) { history.push(loginPath); } return undefined; }; // 如果是登录页面，不执行 if (history.location.pathname !== loginPath) { const currentUser = await fetchUserInfo(); return { fetchUserInfo, currentUser, settings: {}, }; } return { fetchUserInfo, settings: {}, }; } // ProLayout 支持的api https://procomponents.ant.design/components/layout export const layout = ({ initialState }) =&gt; { return { rightContentRender: () =&gt; <RightContent /&gt;, disableContentMargin: false, waterMarkProps: { content: initialState?.currentUser?.user?.userName, }, menu: { // 每当 initialState?.currentUser?.userid 发生修改时重新执行 request params: { userId: initialState?.currentUser?.user?.id, }, request: async (params, defaultMenuData) =&gt; { // initialState.currentUser 中包含了所有用户信息 return menuData; }, }, footerRender: () =&gt; <Footer /&gt;, onPageChange: () =&gt; { const { location } = history; // 如果没有登录，重定向到 login if (!initialState?.currentUser &amp;&amp; location.pathname !== loginPath) { history.push(loginPath); } }, links: isDev ? [ // <Link to="/umi/plugin/openapi" target="_blank"&gt; // <LinkOutlined /&gt; // <span&gt;OpenAPI 文档</span&gt; // </Link&gt;, // <Link to="/~docs"&gt; // <BookOutlined /&gt; // <span&gt;业务组件文档</span&gt; // </Link&gt;, ] : [], menuHeaderRender: undefined, menuDataRender: () =&gt; fixMenuItemIcon(menuData), disableContentMargin: true, // 自定义 403 页面 // unAccessible: <div&gt;unAccessible</div&gt;, ...initialState?.settings, }; }; 然后在顶部多页tab中不能正常显示菜单的中英文，只能显示菜单的 name属性里面的文案 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

我看了此插件的源码，用的是route的name。
后端返回的menus数据结构也有name属性的，也定义了国际化

"name":"StockControl",

'menu.StockControl': 'Stock Control',

**Comment by fangzhengjin** [comment]
请提供可复现的仓库
