### ISSUE TITLE
antd pro V5 退出登录，如何清空tabs里的菜单呢？[Question]

### ISSUE THREAD

**Issue by ajunc** [fangzhengjin/umi-plugin-panel-tabs#12]
目前退出登录，再次登录，还会显示上一次已存在的tabs

在logout()中調用  closeAll()  钩子就ok

**Comment by fangzhengjin** [comment]
退出登录怎么会还显示之前的tabs呢? 除非你退出登录后没有用window.location.href重定向到登录页
