### ISSUE TITLE
[Bug] 登录页面也会显示

### ISSUE THREAD

**Issue by lifegit** [fangzhengjin/umi-plugin-panel-tabs#13]
<img width="2559" alt="image" src="https://user-images.githubusercontent.com/33006878/157217096-76a26995-d6f4-4e5a-a925-00dbd557f383.png">

**Comment by fangzhengjin** [comment]
登录页不要在路由写name, 有name就有标签页，或者在name下方再加一个配置，hideInPanelTab: true,也可以在标签中隐藏

**Comment by fangzhengjin** [comment]
登录页不要在路由写name, 有name就有标签页，或者在name下方再加一个配置，hideInPanelTab: true,也可以在标签中隐藏

**Comment by lifegit** [comment]
感谢！成功了！
