### ISSUE TITLE
会使路由权限失败

### ISSUE THREAD

**Issue by Aqpcet** [fangzhengjin/umi-plugin-panel-tabs#14]
### bug 描述
使用antd prov5的access时，会使路由权限失败

### 期望结果
请更新umi-plugin-keep-alive依赖到最新版本，这个版本解决了这个bug

### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangzhengjin** [comment]
0.0.19 已发布
