### ISSUE TITLE
标签栏和菜单栏标题不一样，请问是哪里出现问题了

### ISSUE THREAD

**Issue by changlin0501** [fangzhengjin/umi-plugin-panel-tabs#16]
### 解决方案

标签栏和菜单栏标题不一样，请问是哪里出现问题了
### 其他信息

![image](https://user-images.githubusercontent.com/47729295/158498696-00e725ed-5f40-4603-a62b-60fbda9fa51e.png)

**Comment by fangzhengjin** [comment]
route.ts app.ts 代码贴一下, 是否开启了国际化?

**Comment by changlin0501** [comment]
![image](https://user-images.githubusercontent.com/47729295/158513846-fadac407-d98a-4ee4-b648-e98c08a868eb.png)
![image](https://user-images.githubusercontent.com/47729295/158513886-12810a0c-06f0-41fa-b579-c50ef24b1a24.png)
应该开启的，菜单切换语言都有的

**Comment by fangzhengjin** [comment]
用的不是antd pro v5吗? 没看到app.ts 
router.ts把字典管理哪里截出来, 或者直接代码贴上来

**Comment by changlin0501** [comment]
我是在BasicLayout 设置布局的

**Comment by changlin0501** [comment]
{
                path: '/system/dictionary',
                name: 'dictionary.management',
                iconfont: 'icon-yonghuguanli',
                icon: 'list',
                component: './system/dictionary',
              },

字典

**Comment by fangzhengjin** [comment]
你设置的国际化是dictionary.management还是menu.dictionary.management ?

**Comment by changlin0501** [comment]
设置的是menu.dictionary.management

**Comment by changlin0501** [comment]
![image](https://user-images.githubusercontent.com/47729295/158523266-7d0696aa-b45c-489d-a454-5f850cbaa4a9.png)

**Comment by changlin0501** [comment]
我用的是antd pro v4

**Comment by fangzhengjin** [comment]
你这真的是太拖拉了...我都不想回了
示例没有, 让你贴代码你不贴, 截图还截不全, 还得追着问, 看不到代码还得猜你的问题是啥
你仔细看看你截图红框里的国际化配置是这个吗`menu.dictionary.management`

**Comment by changlin0501** [comment]
抱歉，让你久等了，今天因为疫情关系，公司让居家隔离收拾东西耽误了，我设置的国际化配置是menu.system-setup.dictionary.management

**Comment by fangzhengjin** [comment]
你现在的问题应该不是插件的问题 是你自己配置的国际化没匹配上 你定义的key和你菜单里的不一致

**Comment by fangzhengjin** [comment]
你每次截图贴代码 就那一小块 上下文我也看不到 我就只能猜到这些了, 国际化匹配那块去看看官方文档吧

**Comment by changlin0501** [comment]
好的，我再试试，谢谢了
