### ISSUE TITLE
使用antdpro V4源码  出现标签栏标题不一致

### ISSUE THREAD

**Issue by changlin0501** [fangzhengjin/umi-plugin-panel-tabs#17]
### 需求描述

使用antdpro V4源码  出现标签栏标题不一致

### 其他信息

![image](https://user-images.githubusercontent.com/47729295/158777936-347e9c60-6340-476f-909d-320407362843.png)

**Comment by fangzhengjin** [comment]
把你这个库提交下我看看?

**Comment by changlin0501** [comment]
> 把你这个库提交下我看看?

https://github.com/changlin0501/antpro-V4 请查看

**Comment by fangzhengjin** [comment]
0.0.20 已发布

**Comment by changlin0501** [comment]
> 0.0.20 已发布

好的，谢谢！
