### ISSUE TITLE
[Feature]可否提供一个选项，关闭此插件的国际化

### ISSUE THREAD

**Issue by luckzhu** [fangzhengjin/umi-plugin-panel-tabs#18]
### 需求描述
你好，能提供一个选项，彻底关闭i18n国际化吗

当使用antd-pro v5，彻底关闭了国际化时，使用此插件可正常使用，但是会有menu国际化没有配置的警告。可否像layout那样增加一个配置，类似于 
 layout: {
    locale: false
  },
可以关闭此插件的国际化

**Comment by fangzhengjin** [comment]
0.0.21 已发布, 参考autoI18n配置
