### ISSUE TITLE
使用panelTab,umi编译报错

### ISSUE THREAD

**Issue by dudongbin** [fangzhengjin/umi-plugin-panel-tabs#2]
"umi": "^3.5.17"
"antd": "^4.14.0"
脚手架用的的antd-pro V5
![image](https://user-images.githubusercontent.com/17821923/139392278-4d5ee367-9eeb-401b-b1a8-1b0b1f08ef9f.png)

**Comment by fangzhengjin** [comment]
看提示 缺少依赖 `@umijs/plugin-access`
另外项目最好是基于 antd-pro V5 ts 来运行, 因为插件的模板使用的是ts, js项目可能无法编译此模板
