### ISSUE TITLE
@umijs/plugin-access 加载失败

### ISSUE THREAD

**Issue by bluef1ash** [fangzhengjin/umi-plugin-panel-tabs#20]
与 #2 相同的问题，我用的是ant design pro V5，如果增加 ` @umijs/plugin-access`  依赖会报错

```shell
plugin @umijs/plugin-access is already registered by /node_modules/@umijs/plugin-access/lib/index.js, plugin from
/node_modules/@umijs/plugin-access/lib/index.js register failed.
```

如果不增加依赖，就会报 #2

**Comment by fangzhengjin** [comment]
给个复现仓库

**Comment by bluef1ash** [comment]
> 给个复现仓库

https://github.com/bluef1ash/phone-number-manager/tree/feature-tabs/frontend

**Comment by fangzhengjin** [comment]
> > 给个复现仓库
> 
> [https://github.com/bluef1ash/phone-number-manager/tree/feature-tabs/frontend](https://github.com/bluef1ash/phone-number-manager/tree/feature-tabs/frontend?rgh-link-date=2022-04-12T13%3A52%3A37Z)

这是一个umi的锅, 详见这里: https://github.com/umijs/plugins/issues/779

解决方法, 将package.json里的`@umijs/plugin-access`移除, 在config.ts中增加`access: {}`配置项

**Comment by bluef1ash** [comment]
> > > 给个复现仓库
> > 
> > 
> > [https://github.com/bluef1ash/phone-number-manager/tree/feature-tabs/frontend](https://github.com/bluef1ash/phone-number-manager/tree/feature-tabs/frontend?rgh-link-date=2022-04-12T13%3A52%3A37Z)
> 
> 这是一个umijs的锅, 你用的umijs版本太新了, 详见这里: [umijs/plugins#779](https://github.com/umijs/plugins/issues/779)
> 
> 解决方法, 将package.json里的`@umijs/plugin-access`移除, 在config.ts中增加`access: {}`配置项

增加 `access: {}` 后，约定式 `src/access.ts` 失效，有什么解决方案吗？
