### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by pei-open** [fangzhengjin/umi-plugin-panel-tabs#21]
国际化显示有问题：

route配置：

      {
        path: '/sync/dashboard',
        name: 'dashboard',
        icon: 'dashboard',
        component: './sync/Dashboard',
      },
      {
        path: '/sync/task',
        name: 'task',
        icon: 'cloudSync',
        component: './sync/Dashboard',
      },

config配置：
  panelTab: {
    use404: true,
    useAuth: true,
    autoI18n: true
  },

i18n内容：
  'menu.sync': '数据同步',
  'menu.sync.dashboard': '任务大盘',
  'menu.sync.task': '同步任务',

显示内容：

![image](https://user-images.githubusercontent.com/31610839/162708237-8ca2fdfa-ffd1-4cb4-84be-e6c5bcd53d34.png)

**Comment by pei-open** [comment]
版本号：0.0.25

**Comment by fangzhengjin** [comment]
已在0.0.26中修复
