### ISSUE TITLE
[Bug]不支持主题

### ISSUE THREAD

**Issue by zhangpengju666** [fangzhengjin/umi-plugin-panel-tabs#23]
### bug 描述

修改主题色后无法应用到Tab

### 复现步骤

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/31264180/163669283-54212f45-86cd-4dc0-a561-0e6428e292ce.png">

**Comment by fangzhengjin** [comment]
暂无计划，欢迎PR



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月16日(周六) 下午5:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [fangzhengjin/umi-plugin-panel-tabs] [Bug]不支持主题 (Issue #23)




 
bug 描述
 
修改主题色后无法应用到Tab
 
复现步骤

**Comment by fangzhengjin** [comment]
已在0.0.27中支持
