### ISSUE TITLE
antpro V4 可以使用吗

### ISSUE THREAD

**Issue by changlin0501** [fangzhengjin/umi-plugin-panel-tabs#28]
### © 版本信息

- Ant Design Pro 版本: [e.g. 4.0.0]
- umi 版本
- 浏览器环境
- 开发环境 [e.g. mac OS]

**Comment by fangzhengjin** [comment]
请自行测试下，本插件测试是基于v5



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月27日(周三) 上午10:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [fangzhengjin/umi-plugin-panel-tabs] antpro V4 可以使用吗 (Issue #28)




 
bug 描述
 
复现步骤
 
期望结果
 
复现代码
 
© 版本信息
  
Ant Design Pro 版本: [e.g. 4.0.0] 

umi 版本 

浏览器环境 

开发环境 [e.g. mac OS] 
 
其他信息
