### ISSUE TITLE
[Bug] access.ts中直接返回true的可以正常显示，()=>true 会403; demo分支可复现

### ISSUE THREAD

**Issue by mtianyan** [fangzhengjin/umi-plugin-panel-tabs#29]
### bug 描述

```
    authorize1: true,
    authorize2: () => true,
```

access.ts中 authorize1返回true的可以正常显示，authorize2 ()=>true 会403

### 复现步骤

拉取最新干净的demo分支代码。

access.ts中添加代码:

```js
    authorize1: true,
    authorize2: () => true,
```

routes.ts

```js
      {
        name: 'basic-form',
        icon: 'smile',
        path: '/form/basic-form',
        access: 'authorize1',
        component: './form/basic-form',
      },
      {
        name: 'step-form',
        icon: 'smile',
        access: 'authorize2',
        path: '/form/step-form',
        component: './form/step-form',
      },
```

basic-form 可正常显示；step-form 403了。

<img width="573" alt="image" src="https://user-images.githubusercontent.com/15145231/165913285-8f5bd6de-62b2-444e-a10a-1bba77184539.png">

<img width="796" alt="image" src="https://user-images.githubusercontent.com/15145231/165913456-de7374dd-8c98-4a04-a626-7c7578ae59e7.png">

### 期望结果

authorize1 与 authorize2页面可在返回true时正常显示

### 复现代码

https://github.com/FullStackPlan/umi-plugin-panel-tabs-bug

### © 版本信息

与最新demo分支完全一致

**Comment by mtianyan** [comment]
@fangzhengjin 麻烦您有空了看下这个问题。谢谢！

**Comment by fangzhengjin** [comment]
你的用法应该是错了吧，access.ts返回的应该是key为string, value为true/false的对象



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月6日(周五) 上午9:33
收件人: ***@***.***&gt;;
抄送: "ZhengJin ***@***.******@***.***&gt;;
主题: Re: [fangzhengjin/umi-plugin-panel-tabs] [Bug] access.ts中直接返回true的可以正常显示，()=&gt;true 会403; demo分支可复现 (Issue #29)




 
@fangzhengjin 麻烦您有空了看下这个问题。谢谢！

**Comment by mtianyan** [comment]
@fangzhengjin  用法里是可以传入函数的，canAccessMenu: (route: any) => {//根据route逻辑 return true}。没使用demo工程，直接创建了一个新antd prov5项目再安装umi-plugin-panel-tabs。问题没有复现了。抱歉了，应该与您这个项目无关。
