### ISSUE TITLE
参数类型定义错误，顺便问下可以支持国际化吗？

### ISSUE THREAD

**Issue by AndroidMilk** [fangzhengjin/umi-plugin-panel-tabs#3]
![image](https://user-images.githubusercontent.com/13392610/142097108-096a7474-133d-441a-9f25-f68264a346e5.png)

1.这里圈红的地方应该定义成string类型
2.希望支持标签国际化

**Comment by fangzhengjin** [comment]
1. 已修复
2. 0.0.14版本已支持国际化, 欢迎反馈👏🏻
