### ISSUE TITLE
[Bug] routes.js 无法正常显示 icon

### ISSUE THREAD

**Issue by chenyu1990** [fangzhengjin/umi-plugin-panel-tabs#32]
### bug 描述
`routes.js` 中的 `icon` 无法正常显示。

### © 版本信息
"@ant-design/icons": "^4.7.0",
"antd": "^4.19.0",
"umi": "^3.5.0"

删除这个插件后，恢复正常

**Comment by fangzhengjin** [comment]
请提供可复现仓库

**Comment by chenyu1990** [comment]
要正常使用这个组件，要把node_modules
