### ISSUE TITLE
标签与内容产生的空白区域问题

### ISSUE THREAD

**Issue by houkunlin** [fangzhengjin/umi-plugin-panel-tabs#34]
https://github.com/fangzhengjin/umi-plugin-panel-tabs/blob/a602d3d219146fc959c023844b19bc11bd29c555/src/Wrappers/PanelTabsWrapper.tsx.tpl#L63

在上面设置了 marginTop: 60 但是 PanelTabs 实际的高度只有 38，这里导致了标签与底部的内容产生了一段空白区域，看起来不太友好

**Comment by fangzhengjin** [comment]
有出现显示问题的截图吗？这个是特意多留出的空间，和内容保持间距，如果你的内容使用了pageContainter包裹，应该不会有显示问题

**Comment by houkunlin** [comment]
既然是特意留出来的那就没问题了
