### ISSUE TITLE
[Question]请教umi3中如何使用该插件

### ISSUE THREAD

**Issue by Liuminke1996** [fangzhengjin/umi-plugin-panel-tabs#35]
### 问题描述

1.yarn add umi-plugin-panel-tabs
2.自动加载umi-plugin
3.umirc.ts中添加panelTab配置
4.根据后台返回的动态路由显示路由列表
5.现在的问题是不知道怎么在页面上添加panelwrapper layout 请指教

**Comment by fangzhengjin** [comment]
没有明白你的意思
1. `routes.ts`路由定义应该是在前端项目中打包前就配置好的, 你所指的后台返回路由信息, 我理解的是layout中的菜单展示, 菜单展示和`routes.ts`定义无关, 只要菜单项点击时跳转到`routes.ts`中定义好的路径即可, 根据ant-design-pro提供的`access.ts`会鉴定用户是否有权限访问当前路由
2. `umi-plugin-panel-tabs`使用的wrapper是在项目启动/编译时自动织入的, 不需要手动操作

**Comment by Liuminke1996** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Liuminke1996** [comment]
谢谢回复，你理解的是对的， 是我的问题，每个需要显示的路由必须有name这个key （其实文档写了 是我太粗心了）
