### ISSUE TITLE
AntDeisgn Pro Table BetaSchemaForm 踩坑指南

### ISSUE THREAD

**Issue by chenyu1990** [fangzhengjin/umi-plugin-panel-tabs#36]
使用 ProTable BetaSchemaForm 的朋友们，一定要用手动控制缓存 [useAliveController](https://github.com/CJY0208/react-activation/blob/master/README_CN.md#%E6%89%8B%E5%8A%A8%E6%8E%A7%E5%88%B6%E7%BC%93%E5%AD%98)
在编辑成功后，一定要 refresh(headerTitle)，不然再次编辑是空白的

登录前后建议都 clear 一下缓存。

**Comment by chenyu1990** [comment]
@fangzhengjin 请教一下
我现在 BetaSchemaForm 在 onClouse/onCancel 时，如果不 refresh，就是空白， refresh了又老是重新请求当前页面的数据

**Comment by fangzhengjin** [comment]
没有用过这个组件，可以提供可复现的仓库吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月4日(周六) 晚上8:42
收件人: ***@***.***&gt;;
抄送: "ZhengJin ***@***.******@***.***&gt;;
主题: Re: [fangzhengjin/umi-plugin-panel-tabs] AntDeisgn Pro Table BetaSchemaForm 踩坑指南 (Issue #36)




 
@fangzhengjin 请教一下
 我现在 BetaSchemaForm 在 onClouse/onCancel 时，如果不 refresh，就是空白， refresh了又老是重新请求当前页面的数据
