### ISSUE TITLE
[Question]tab没有成功汉化

### ISSUE THREAD

**Issue by 736473283** [fangzhengjin/umi-plugin-panel-tabs#38]
### 问题描述

我左边的菜单是可以正常汉化，但是tab上的一直还是显示未汉化的内容。
菜单是从后台动态返回的

### 其他信息

![image](https://user-images.githubusercontent.com/24606375/173616225-99e355a5-2b0e-4aaf-83a2-32fce582b5d1.png)

**Comment by fangzhengjin** [comment]
提供可复现仓库



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 14, 2022 23:28 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [fangzhengjin/umi-plugin-panel-tabs] [Question] (Issue #38)




 
问题描述
 
我左边的菜单是可以正常汉化，但是tab上的一直还是显示未汉化的内容。
 菜单是从后台动态返回的
 
其他信息

**Comment by 736473283** [comment]
> 提供可复现仓库
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, Jun 14, 2022 23:28 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [fangzhengjin/umi-plugin-panel-tabs] [Question] (Issue #38) 问题描述 我左边的菜单是可以正常汉化，但是tab上的一直还是显示未汉化的内容。 菜单是从后台动态返回的 其他信息 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;
已将代码放到仓库中：https://github.com/736473283/sa-auth-react-ui.git

**Comment by fangzhengjin** [comment]
看了下你提供的仓库, 发现以下几处问题:

1. 该插件默认不开启国际化模式, 需要在`config.ts`中[配置](https://github.com/fangzhengjin/umi-plugin-panel-tabs#%E9%85%8D%E7%BD%AE%E9%A1%B9)
2. 标签栏位置出现偏移, #26 第2条
3. header白条随页面滚动, `defaultSettings.ts`中`fixedHeader: true`
4. 列表页在标签下方出现了标题和面包屑, 在对应页面中给`PageContainer`增加两个属性`title={false}` `breadcrumb={undefined}`
5. 将面包屑放到header中, 在`app.ts`的`layout`函数中返回值加入`headerContentRender: () => <ProBreadcrumb />`
