### ISSUE TITLE
建议补充一下文档

### ISSUE THREAD

**Issue by biggbb777** [fangzhengjin/umi-plugin-panel-tabs#4]
插件做得很不错。
一个小小的建议：因为使用者可能会需要手动控制缓存，例如`import { useAliveController } from 'umi'`，所以建议补充一下react-activation相关的内容或链接，这样功能可能会更直观一点。

**Comment by biggbb777** [comment]
同一路由多份缓存该如何实现？例如：
![image](https://user-images.githubusercontent.com/44860359/150259338-4cd52242-6bf7-4253-96f9-2b19046848d2.png)

**Comment by fangzhengjin** [comment]
文档已补充, 暂时还不支持多份缓存, 欢迎PR👏🏻
