### ISSUE TITLE
使用了之后会导致水印不显示，不知各位有没有遇到这个问题。

### ISSUE THREAD

**Issue by findbys** [fangzhengjin/umi-plugin-panel-tabs#50]

**Comment by fangzhengjin** [comment]
演示环境是正常显示水印的哈，可以先检查下配置，如果不确定可以提供复现仓库



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月25日(周四) 上午9:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [fangzhengjin/umi-plugin-panel-tabs] 使用了之后会导致水印不显示，不知各位有没有遇到这个问题。 (Issue #50)

**Comment by findbys** [comment]
> 演示环境是正常显示水印的哈，可以先检查下配置，如果不确定可以提供复现仓库
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年8月25日(周四) 上午9:52 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [fangzhengjin/umi-plugin-panel-tabs] 使用了之后会导致水印不显示，不知各位有没有遇到这个问题。 (Issue #50) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

是的啊，我看演示环境能正常显示水印。应该是我自己的配置问题，我仔细检查下，感谢百忙之中及时回复解答！

**Comment by findbys** [comment]
> > 演示环境是正常显示水印的哈，可以先检查下配置，如果不确定可以提供复现仓库
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年8月25日(周四) 上午9:52 收件人: _**@**_.**_>; 抄送: _**@**_._**>; 主题: [fangzhengjin/umi-plugin-panel-tabs] 使用了之后会导致水印不显示，不知各位有没有遇到这个问题。 (Issue #50) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: _**@**_.**_>
> 
> 是的啊，我看演示环境能正常显示水印。应该是我自己的配置问题，我仔细检查下，感谢百忙之中及时回复解答！

1：单独在PageContainer设置了水印就能生效
<img width="466" alt="image" src="https://user-images.githubusercontent.com/59687677/186563348-bdc8cb78-502d-4469-9d59-853cdbd7c741.png">
2：在app.tsx里配置全局水印不会生效，奇怪了
<img width="513" alt="image" src="https://user-images.githubusercontent.com/59687677/186563805-fbf12fcc-200f-47b5-91ad-05e7c1648375.png">

**Comment by fangzhengjin** [comment]
可以zindex该小点试试

**Comment by Lanlanxiao** [comment]
请问这个问题有解决方法吗，我的面包屑配置也是使用了这个插件后显示不出来

**Comment by fangzhengjin** [comment]
zIndex设置成1看看效果吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月25日(周四) 上午10:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fangzhengjin/umi-plugin-panel-tabs] 使用了之后会导致水印不显示，不知各位有没有遇到这个问题。 (Issue #50)




   
演示环境是正常显示水印的哈，可以先检查下配置，如果不确定可以提供复现仓库
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年8月25日(周四) 上午9:52 收件人: _@**._&gt;; 抄送: ***@***.***&gt;; 主题: [fangzhengjin/umi-plugin-panel-tabs] 使用了之后会导致水印不显示，不知各位有没有遇到这个问题。 (Issue #50) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.**_&gt;
  
是的啊，我看演示环境能正常显示水印。应该是我自己的配置问题，我仔细检查下，感谢百忙之中及时回复解答！
  
1：单独在PageContainer设置了水印就能生效
 
 2：在app.tsx里配置全局水印不会生效，奇怪了

**Comment by Lanlanxiao** [comment]
设置成1，也显示不出来,好像是把antd版本库升级到最新，然后水印和面包屑都没出来了，没有使用这个插件时，水印和面包屑配置是正常的
![image](https://user-images.githubusercontent.com/36785311/195307770-5485adfe-34ce-4a3a-9a41-bc1797db0622.png)
![image](https://user-images.githubusercontent.com/36785311/195307939-a0bd3051-344d-4643-8e8e-97f121de4f81.png)

**Comment by findbys** [comment]
我的解决方案是在childrenRender用水印组件单独包一层
<img width="747" alt="image" src="https://user-images.githubusercontent.com/59687677/195327632-d993a2f8-8fe6-48c8-a0f8-7a4da66642d9.png">

**Comment by findbys** [comment]
> 设置成1，也显示不出来，好像是把antd库升级到最新了，然后水印和面包碎片出来了，没有使用这个插件的时候，水印和面包版本配置是正常的 ![图片](https://user-images.githubusercontent.com/36785311/195307770-5485adfe-34ce-4a3a-9a41-bc1797db0622.png) ![图片](https://user-images.githubusercontent.com/36785311/195307939-a0bd3051-344d-4643-8e8e-97f121de4f81.png)

在layout中的childrenRender单独用水印组件包一层就能解决

**Comment by Lanlanxiao** [comment]
> 我的解决方案是在childrenRender用水印组件单独包一层 <img alt="image" width="747" src="https://user-images.githubusercontent.com/59687677/195327632-d993a2f8-8fe6-48c8-a0f8-7a4da66642d9.png">

可以的，谢谢

**Comment by Ygp1024** [comment]
为什么我按照上边的用组建包裹还是不显示水印呢
