### ISSUE TITLE
[Question] tab最右侧的左右箭头目前是不是没有任何作用？如果是的话是否可以隐藏？

### ISSUE THREAD

**Issue by js515990** [fangzhengjin/umi-plugin-panel-tabs#51]
tab行最右侧的两个箭头似乎没有作用

**Comment by fangzhengjin** [comment]
当标签超出屏幕范围后，你会感受到他的作用～😁



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月7日(周三) 中午1:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [fangzhengjin/umi-plugin-panel-tabs] [Question] tab最右侧的左右箭头目前是不是没有任何作用？如果是的话是否可以隐藏？ (Issue #51)




 
tab行最右侧的两个箭头似乎没有作用

**Comment by js515990** [comment]
soga!
👍
