### ISSUE TITLE
IE11支持吗？

### ISSUE THREAD

**Issue by r632420050** [fangzhengjin/umi-plugin-panel-tabs#52]
### 问题描述
在谷歌浏览器测试正常，在IE下不能正常使用，提示错误"“SVGGraphicsElement”未定义

本地环境：
 "umi": "^3.5.0",
"antd": "^4.17.0",
"@ant-design/pro-cli": "^2.1.0",

### 其他信息

![image](https://user-images.githubusercontent.com/10431709/190605336-dff03264-baeb-49a2-a987-2d4811dbfa93.png)

**Comment by fangzhengjin** [comment]
看样子ie11对svg支持有问题。。换edge把


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月16日(周五) 下午5:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [fangzhengjin/umi-plugin-panel-tabs] IE11支持吗？ (Issue #52)




 
问题描述
 
在谷歌浏览器测试正常，在IE下不能正常使用，提示错误"“SVGGraphicsElement”未定义
 
本地环境：
 "umi": "^3.5.0",
 "antd": "^4.17.0",
 ***@***.***/pro-cli": "^2.1.0",
 
其他信息
 

 
&mdash;

**Comment by r632420050** [comment]
主要这个项目必须是在IE下运行，还切换不了，另外在切换路由时，就一直提示未响应
![image](https://user-images.githubusercontent.com/10431709/190937310-68856a35-0ee7-4d8a-a8f9-5105b5c83330.png)

**Comment by fangzhengjin** [comment]
我们没有项目在IE下运行, 可能无法帮到你, 或许你可以fork一份将svg替换为png试试?
