### ISSUE TITLE
大佬们怎么自定义他的样式啊，这个样式无法修改吗

### ISSUE THREAD

**Issue by yuanritian1** [fangzhengjin/umi-plugin-panel-tabs#53]
不能定义它的样式吗比如换颜色换图标这些

**Comment by fangzhengjin** [comment]
看完文档再来提问



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月17日(周六) 下午5:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [fangzhengjin/umi-plugin-panel-tabs] 大佬们怎么自定义他的样式啊，这个样式无法修改吗 (Issue #53)




 
不能定义它的样式吗比如换颜色换图标这些
