### ISSUE TITLE
antd design pro 5安装运行报错怎么解决呢？

### ISSUE THREAD

**Issue by ajunc** [fangzhengjin/umi-plugin-panel-tabs#6]
22mf-va_remoteEntry.js:915 Uncaught (in promise) Error: Module "./react-activation" does not exist in container.
while loading "./react-activation" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:915:11
(anonymous) @ mf-va_remoteEntry.js:915
DevTools failed to load source map: Could not parse content for http://localhost:8000/react-router.js.map: Unexpected token < in JSON at position 0
mf-va_remoteEntry.js:915 Uncaught (in promise) Error: Module "./react-activation" does not exist in container.
while loading "./react-activation" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:915:11
(anonymous) @ mf-va_remoteEntry.js:915
2DevTools failed to load source map: Could not parse content for http://localhost:8000/index.js.map: Unexpected token < in JSON at position 0
3mf-va_remoteEntry.js:915 Uncaught (in promise) Error: Module "./E:/psi/psi-ui/node_modules/warning/warning.js" does not exist in container.
while loading "./E:/psi/psi-ui/node_modules/warning/warning.js" from webpack/container/reference/mf
    at mf-va_remoteEntry.js:915:11
(anonymous) @ mf-va_remoteEntry.js:915
DevTools failed to load source map: Could not parse content for http://localhost:8000/invariant.js.map: Unexpected token < in JSON at position 0
-----------------------------------------
antd design pro 5我安装了这个插件，报错了，请问怎么解决呢(公司不能上传截图。。。)

**Comment by fangzhengjin** [comment]
看样子是依赖问题, 手动安装下这个依赖试试 `umi-plugin-keep-alive`

**Comment by ajunc** [comment]
> 看样子是依赖问题, 手动安装下这个依赖试试 `umi-plugin-keep-alive`

手动删除一下 .umi 临时文件，重启就好啦
