### ISSUE TITLE
最新版本的问题，启动项目后。routers中生成的tab路径和umi中tab文件路径不同 。

### ISSUE THREAD

**Issue by Ygp1024** [fangzhengjin/umi-plugin-panel-tabs#63]

**Comment by Ygp1024** [comment]
> ### 问题描述
> ### 示例代码
> ### 其他信息

**Comment by Ygp1024** [comment]
![image](https://user-images.githubusercontent.com/116085107/207218613-9f9aa4ec-24ed-4472-b3d4-eca93c082b84.png)

**Comment by hui-huo** [comment]
@Ygp1024 你是怎么解决的。。

**Comment by Ygp1024** [comment]
未解决，我现在下载的是0.0.28版本



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月14日 09:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [fangzhengjin/umi-plugin-panel-tabs] 最新版本的问题，启动项目后。routers中生成的tab路径和umi中tab文件路径不同 。 (Issue #63) |

@Ygp1024 你是怎么解决的。。

**Comment by hui-huo** [comment]
@Ygp1024 好吧 我也先试试

**Comment by Ygp1024** [comment]
@fangzhengjin 这最新版本问题大佬能看一下吗？
