### ISSUE TITLE
某些页面会出现两个tabs的实例

### ISSUE THREAD

**Issue by ajunc** [fangzhengjin/umi-plugin-panel-tabs#7]
官网安装的的antd pro v5，使用了此插件，在 列表页/搜索列表/搜索列表（文章）  页面会出现两个 多页签tabs 的实例，这是属于bug吗(抱歉公司网络没法发图)

**Comment by fangzhengjin** [comment]
测试环境开启了热重载会出现此问题, 打包后不会出现
