### ISSUE TITLE
config.js里面的国际化怎么配置呢？文档有点点不太详细(刚搞react不太懂)

### ISSUE THREAD

**Issue by ajunc** [fangzhengjin/umi-plugin-panel-tabs#8]
`panelTab: {
    use404: true,
    useAuth: true,
    autoI18n: true,
    tabsLimit: 10,
    tabsLimitWait: 500,
    tabsLimitWarnTitle: <FormattedMessage id="panelTab.tabsLimitWarnTitle" />,
    tabsLimitWarnContent: <FormattedMessage id="panelTab.tabsLimitWarnContent" />,
  },`

**Comment by ajunc** [comment]
> `panelTab: { use404: true, useAuth: true, autoI18n: true, tabsLimit: 10, tabsLimitWait: 500, tabsLimitWarnTitle: <FormattedMessage id="panelTab.tabsLimitWarnTitle" />, tabsLimitWarnContent: <FormattedMessage id="panelTab.tabsLimitWarnContent" />, },`

好吧，我自问自答一下，哈哈。直接写国际化字符串就好了

tabsLimitWarnTitle: 'panelTab.tabsLimitWarnTitle',
tabsLimitWarnContent: 'panelTab.tabsLimitWarnTitle',

**Comment by fangzhengjin** [comment]
按[国际化配置项](https://github.com/fangzhengjin/umi-plugin-panel-tabs#%E5%9B%BD%E9%99%85%E5%8C%96%E9%85%8D%E7%BD%AE%E9%A1%B9)在`locale/zh-CN.ts`配置语言文件就可以了,配置方法见[ant-design-pro菜单国际化](https://pro.ant.design/zh-CN/docs/layout/#%E8%8F%9C%E5%8D%95%E5%9B%BD%E9%99%85%E5%8C%96)

**Comment by fangzhengjin** [comment]
开启了国际化不建议在config.ts中配置语言标签和国际化字符串
