### ISSUE TITLE
多标签样式错乱

### ISSUE THREAD

**Issue by rongxingsun** [fangzhengjin/umi-plugin-panel-tabs#9]
![图片](https://user-images.githubusercontent.com/12825624/153313107-ac7b3d76-69a7-4d43-b249-1b3d41d4eb58.png)

**Comment by fangzhengjin** [comment]
请提供可复现的最小仓库或线上环境(codesandbox)

**Comment by ajunc** [comment]
> 请提供可复现的最小仓库或线上环境(codesandbox)

应该是在Safari浏览器会出现这种情况

**Comment by fangzhengjin** [comment]
Safari测试未发现此问题, 如需重新开启此问题请提供可复现的仓库
